baseURL: 'https://linbo-lin.github.io/'
languageCode: 'en-us'
title: 'Begin Now'
theme: 'PaperMod'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
  disableXML: true
  minifyOutput: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Begin Now
  description: "Begin Now"
  keywords: [Blog, Portfolio, PaperMod]
  author: ""
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Begin Now"
    icon: /apple-touch-icon.png
    iconHeight: 35

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
